# tasks file
---
- name: stop service
  ansible.builtin.service:
    name: apparmor
    state: stopped
  failed_when: false
  tags:
    - configuration
    - apparmor

- name: remove service
  ansible.builtin.service:
    name: apparmor
    enabled: false
  failed_when: false
  tags:
    - configuration
    - apparmor

- name: remove package
  ansible.builtin.apt:
    name: apparmor
    state: absent
    purge: true
  tags:
    - configuration
    - apparmor
