# tasks file for apparmor
---
- name: stop service
  service:
    name: apparmor
    state: stopped
  failed_when: false
  tags:
   - configuration
   - apparmor

- name: remove service
  service:
    name: apparmor
    enabled: false
  failed_when: false
  tags:
   - configuration
   - apparmor

- name: remove package
  apt:
    name: apparmor
    state: absent
    purge: true
  tags:
    - configuration
    - apparmor
